### ISSUE TITLE
Test failure message should contain original error message.

### ISSUE THREAD

**Issue by zahir033** [getgauge/xml-report#1]
Twist used to print customized error message in  test case  failure message. But gauge simply prints hard coded error message like "Step Execution Failure" and it's pretty much unreal to go through the stack trace every time rather than knowing which is original cause of the error.

**Comment by apoorvam** [comment]
@zahir033 The custom error message should be shown in xml-report too. However, other report plugins do show the custom error message.

**Comment by kashishm** [comment]
We have released [XML-Report 0.1.1](https://github.com/getgauge/xml-report/releases/tag/v0.1.1) with the fix. Update the plugin by running the following command:
```
gauge --update xml-report
```
Feel free to reopen this issue, if you face any problem.

**Comment by zahir033** [comment]
Appreciate your help. But  I noticed new version of xml report is working with only Gauge java 0.2.1 version. If I use any higher version of java plugin, gauge is not able to run the specs. Forcefully I had to  downgrade java plugin version. Can you please take a look into this one?

**Comment by kashishm** [comment]
We recommend using latest [Gauge 0.2.1](https://github.com/getgauge/gauge/releases/tag/v0.2.1). The following command will update all the plugins installed using Gauge. This command is present in Gauge 0.2.0 & above
```
gauge --update-all
```
