### ISSUE TITLE
Skipped attribute when there are skipped scenarios.  Also missing system-err value

### ISSUE THREAD

**Issue by ocary** [getgauge/xml-report#14]
XML results for skipped scenarios / specs are not the same between xml-report v0.1.3 and v0.2.0

This is causing a problem as we are doing results processing on the testsuite attribute; skipped specs weren't being reported as skipped.

### Expected behavior
The testsuite tag to have an attribute with the number of skipped scenarios.

### Actual behavior
Testsuite does not have a skipped attribute even when there are skipped scenario(s).

### Steps to reproduce
1.  Create a spec with an unimplemented step.
2.  In a terminal window, run the spec
3.  As expected in the terminal, observe the results shows skipped spec and scenario.
4.  Open the result.xml file
5.  Observe that the testsuite tag does not have a 'skipped' attribute.    <-   Issue.
6.  Observe that the system-error tag does not have a value.    <-  Issue.

### Gauge version
Gauge version: 0.9.7

Plugins
-------
csharp (0.10.3)
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
json-report (0.2.1)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

Sample v0.2.0 output.   Missing attribute and value.
```
<testsuites>
	<testsuite id="1" tests="2" failures="0" package="C:\dev\javasample\specs\example.spec" time="0.000" timestamp="2018-04-19T14:36:34" name="Specification Heading" errors="0" hostname="BGTMNWL-C4ZDM32">    **<---  No skipped attribute in there**
		<properties></properties>
		<testcase classname="Specification Heading" name="Vowel counts in single word" time="0.000">
			<skipped message="C:\dev\javasample\specs\example.spec:17 Step implementation not found =&gt; &#39;This does not exist&#39;"></skipped>
		</testcase>
		<testcase classname="Specification Heading" name="Vowel counts in multiple word" time="0.000">
			<skipped message="C:\dev\javasample\specs\example.spec:26 Step implementation not found =&gt; &#39;NewStepNotImplemented&#39;"></skipped>
		</testcase>
		<system-out></system-out>
		<system-err></system-err>     **<----   No value in there.**
	</testsuite>
</testsuites>

```
Sample v0.1.3 output.   Has attribute and value.   Snipped and annonymized XML file from a different spec run.
```
<testsuite id="1" tests="1" failures="0" package="C:\....More.spec" time="0.000" timestamp="2018-04-19T13:01:54" name="...More" errors="0" skipped="1" hostname="...">    **<---- has skipped attribute**
...
<system-err>Validation failed, 1 Scenarios were skipped.</system-err>    <--  Has a value.
```

**Comment by ocary** [comment]
Wow.   Just noticed the sample output I supplied didn't come through.  I'll get that to show up.

**Comment by ocary** [comment]
Corrected original post to have sample XML.

**Comment by sriv** [comment]
Hi @ocary - what does the corresponding html-report look like? Does it have the correct skipped values and message?

Trying to see if this is a issue with xml-report or gauge itself.

**Comment by ocary** [comment]
HTML report shows _skipped_ as expected.

![77](https://user-images.githubusercontent.com/6934721/39652024-c38bc780-4fb1-11e8-87bf-f1bd1571e641.png)

**Comment by sriv** [comment]
gauge-proto needed update. Done. Fix should be available in nightly >= 07-05-2018.
