### ISSUE TITLE
Add Environment details  in XML report.  This is available in html-report, will be nice to have in XML report.

### ISSUE THREAD

**Issue by gaddemani** [getgauge/xml-report#24]
### Expected behavior
<testsuite id="1" tests="1" failures="0" package="C:\xxx\specs\" time="29.377" timestamp="2020-02-28T10:43:13" **env=default/selected environment** name="Test2" errors="0" hostname="XXX">

### Actual behavior
<testsuite id="1" tests="1" failures="0" package="C:\xxx\specs\" time="29.377" timestamp="2020-02-28T10:43:13"  name="Test2" errors="0" hostname="XXX">

### Steps to reproduce
1.
2.
3.

### Gauge version
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
json-report (0.2.2)
screenshot (0.0.1)
xml-report (0.2.2)

**Comment by sriv** [comment]
the xml report generates the output that junit tasks would generate, so that it is easy for CI systems to report on. This puts constraints on what fields can be added to the output.

Consider using json-report if you need more information.
