### ISSUE TITLE
feat: adding arm64 to the multi-arch build

### ISSUE THREAD

**Issue by mholetzko** [getgauge/xml-report#42]
### Expected behavior

Hello everyone, 

we are running our tests in an `arm64` environment. While e.g. the html-plugin has a matching build for `arm64` ([see](https://github.com/getgauge/html-report/releases/download/v4.1.4/html-report-4.1.4-linux.arm64.zip) and [here](https://github.com/getgauge/html-report/blob/9e75689a68d78408ead6c4dd732d0000bf7f96df/build/make.go#L33) ), it is missing for the xml-plugin. 

Just for completeness - the error message :) :

```
Compatible version of plugin xml-report not found. Installing plugin xml-report...
Download URL for 'arm64' architecture is not set for this plugin. Falling back to 'x86_64', but this may cause issues.
Failed to install plugin 'xml-report' version 0.2.3.
Reason: provided plugin is not compatible with OS linux arm64
Unable to start plugin xml-report. Plugin xml-report is not installed. To install, run `gauge install xml-report`.
```
### Acceptance Criteria

 - [x] arm64 build works and is smoke tested on a server
 - [] arm64 build is part of the next release with no further changes on the plugin. (This should keep it 100% backwards compatible)

### Support 

- I can do the PR if you give me a `go` - as far as I can see you have already done a great job in all the plugins to implement multi-arch with a nice abstraction and it should be a one-liner 🤔 
- I would also take over some integration testing on my arm servers

### Plugin version
```
v.0.2.3
https://github.com/getgauge/xml-report/releases/tag/v0.2.3
```

**Comment by zabil** [comment]
Please feel free to send a PR for this

**Comment by mholetzko** [comment]
@zabil That was quick 👯

**Comment by mholetzko** [comment]
@zabil I think I have done all I can do so far. I'd be happy with the solution.
