### ISSUE TITLE
Add spec file name and step line number in case of failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/xml-report#9]
### Expected behavior

In the current failure exception, the report should give the file name and line number in case of failure.
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
